inveniosoftware/invenio-accounts

- invenio_accounts/upgrades/accounts_2014_11_07_usergroup_name_column_unique.py
- invenio_accounts/upgrades/accounts_2015_01_14_add_name_columns.py
- invenio_accounts/upgrades/accounts_2015_03_06_namedefaults.py
- invenio_accounts/upgrades/accounts_2015_03_06_passlib.py
- invenio_accounts/upgrades/accounts_2015_06_26_userext.py
- requirements-devel.txt
- setup.py
* FIX Fixes import of invenio_upgrader in the past upgrade recipes
following its separation into standalone package.
> global: fix import of invenio_upgrader

- .gitignore
- AUTHORS.rst
- CHANGES.rst
- MANIFEST.in
- RELEASE-NOTES.rst
- invenio_accounts/translations/de/LC_MESSAGES/messages.po
- invenio_accounts/translations/es/LC_MESSAGES/messages.po
- invenio_accounts/translations/fr/LC_MESSAGES/messages.po
- invenio_accounts/translations/invenio.pot
- invenio_accounts/translations/it/LC_MESSAGES/messages.po
- invenio_accounts/version.py
- setup.cfg
> Invenio-Accounts v0.1.1

- .travis.invenio.cfg
- .travis.yml
- invenio_accounts/forms.py
- invenio_accounts/helpers.py
- invenio_accounts/models.py
- invenio_accounts/tokens.py
- invenio_accounts/utils.py
- invenio_accounts/views/accounts.py
- setup.py
- tests/test_tokens.py
Removes dependency on *Invenio-Access* module and changes way how the access tokens are generated.
--
cc @lnielsen @hachreak
> global: removal of mailcookie 

- invenio_accounts/fixtures.py
* Removes fixed user id from fixtures as it is automatically generated
by database engine. (closes inveniosoftware/invenio#3320)
> global: fix fixtures loading on PostgreSQL

- .travis.invenio.cfg
- invenio_accounts/bundles.py
- invenio_accounts/forms.py
- invenio_accounts/helpers.py
- invenio_accounts/tokens.py
- invenio_accounts/utils.py
- invenio_accounts/validators.py
- invenio_accounts/views/accounts.py
- invenio_accounts/views/settings.py
- requirements-devel.txt
- setup.py
- tests/test_accounts_user.py
- tests/test_forms.py
* FIX Adds missing `invenio_base` dependency and amends past
upgrade recipes following its separation into standalone package.
> installation: fix invenio_base imports

- examples/app.py
- invenio_accounts/ext.py
* Registers blueprint in order to load default templates.
> accounts: fix blueprint registration

- examples/app.py
- invenio_accounts/cli.py
- invenio_accounts/ext.py
- tests/test_cli.py
- tests/test_invenio_accounts.py
* Changed structure of CLI tool to a 2 levels. (Closes #32)
Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>
> cli: change structure

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_accounts/version.py
> Invenio-Accounts v1.0.0a2

- MANIFEST.in
* Includes *.mo files in MANIFEST.in. (closes #46)
> translations: inclusion of *.mo files in MANIFEST

- examples/app.py
> examples: migration from bower to npm

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_accounts/version.py
> release: v1.0.0a3

- invenio_accounts/models.py
* Fixes issue when manipulating users outside request context.
--
FYI @otron @SamiHiltunen this might solve your issues in tests ...
> models: IP validation hacks

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_accounts/version.py
> release: v1.0.0a5

- setup.py
> i18n: entry point module name fix

- examples/app.py
- invenio_accounts/templates/invenio_accounts/forgot_password.html
- invenio_accounts/testutils.py
- invenio_accounts/views.py
- setup.py
- tests/test_utils.py
> views: settings menu fix + global: flask-security/login upgrade

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_accounts/version.py
> release: v1.0.0a6

- invenio_accounts/templates/invenio_accounts/login_user.html
> templates: blocks and minor color fix

- tests/conftest.py
> tests: no db drop on setup

- tests/e2e/conftest.py
> tests: comment removal

- invenio_accounts/version.py
> version: post-release bump

- tests/test_invenio_accounts.py
* Checks that value in ACCOUNTS_USE_CELERY configuration is respected.
(closes #82)
> tests: respect ACCOUNTS_USE_CELERY configuration

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_accounts/templates/invenio_accounts/register_user.html
- invenio_accounts/version.py
> release: v1.0.0a7

- .travis.yml
- INSTALL.rst
- docs/index.rst
- docs/usage.rst
- invenio_accounts/ext.py
- invenio_accounts/models.py
- invenio_accounts/sessions.py
- invenio_accounts/testutils.py
- setup.py
- tests/conftest.py
- tests/test_models.py
- tests/test_sessions.py
- tests/test_utils.py
Not at all anything like _backyard sessions_.
resolves #51.
> sessions: backend sessions and user activity

- examples/app.py
- invenio_accounts/admin.py
- invenio_accounts/ext.py
- invenio_accounts/models.py
- run-tests.sh
- setup.py
- tests/test_admin.py
Signed-off-by: Bruno Cuc <bruno.cuc@cern.ch>
> global: admin views for invenio-accounts

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_accounts/version.py
> release: v1.0.0a8

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_accounts/version.py
> release: v1.0.0a9

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_accounts/version.py
> release: v1.0.0a10

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_accounts/version.py
> release: v1.0.0a11

- examples/app.py
- invenio_accounts/cli.py
- invenio_accounts/datastore.py
- setup.cfg
- setup.py
- tests/conftest.py
> cli: support for Flask>=0.11

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_accounts/version.py
> release: v1.0.0a13

- examples/app.py
- invenio_accounts/cli.py
- setup.py
- tests/conftest.py
- tests/e2e/conftest.py
- tests/test_invenio_accounts.py
* Removes depedency on Flask-CLI.
> installation: Flask>=0.11

- .gitignore
- MANIFEST.in
- examples/app-recreate.sh
- examples/app.py
- examples/requirements.txt
- tests/test_example_app.py
* Adds test_example_app.py. (closes #147)
> tests: addition of test_example_app.py

- .travis.yml
- AUTHORS.rst
- docs/conf.py
- examples/app-recreate.sh
- invenio_accounts/sessions.py
- invenio_accounts/translations/cs/LC_MESSAGES/messages.po
- invenio_accounts/translations/de/LC_MESSAGES/messages.po
- invenio_accounts/translations/es/LC_MESSAGES/messages.po
- invenio_accounts/translations/fr/LC_MESSAGES/messages.po
- invenio_accounts/translations/it/LC_MESSAGES/messages.po
- setup.py
- tests/test_example_app.py
- tests/test_sessions.py
* Regenereates sessions after user login.
Signed-off-by: Alexander Ioannidis <a.ioannidis@cern.ch>
> sessions: security fixes

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_accounts/version.py
> release: v1.0.0a14

- .travis.yml
- .tx/config
- AUTHORS.rst
- invenio_accounts/translations/cs/LC_MESSAGES/messages.po
- invenio_accounts/translations/da/LC_MESSAGES/messages.po
- invenio_accounts/translations/de/LC_MESSAGES/messages.po
- invenio_accounts/translations/es/LC_MESSAGES/messages.po
- invenio_accounts/translations/fr/LC_MESSAGES/messages.po
- invenio_accounts/translations/it/LC_MESSAGES/messages.po
- invenio_accounts/translations/messages.pot
* Corrects Czech translations as suggested by @helix84.
* Adds German translations.
> i18n: translation improvements

- docs/api.rst
- invenio_accounts/config.py
- invenio_accounts/datastore.py
- invenio_accounts/ext.py
- invenio_accounts/hash.py
- invenio_accounts/models.py
- invenio_accounts/sessions.py
- invenio_accounts/tasks.py
- invenio_accounts/testutils.py
* Improves documentation. (addresses #137)
> docs: addition of param and result sections

- invenio_accounts/admin.py
- tests/conftest.py
- tests/test_admin.py
* Makes available just email and active fields.
Signed-off-by: Diego Rodriguez <diego.rodriguez.rodriguez@cern.ch>
> accounts: create/edit user form fix

- MANIFEST.in
- README.rst
- RELEASE-NOTES.rst
- docs/requirements.txt
- tests/test_sessions.py
> docs: move to readthedocs.io

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_accounts/version.py
> release: v1.0.0a15

- .lgtm
- MAINTAINERS
- MANIFEST.in
- invenio_accounts/version.py
> docs: MAINTAINERS file and LGTM configuration

- run-tests.sh
- tests/conftest.py
- tests/e2e/e2e_basic_test.py
Signed-off-by: Krzysztof Nowak <k.nowak@cern.ch>
> setup: isort glob fixes

- invenio_accounts/ext.py
- setup.py
> cli: migration to entry points

- .editorconfig
- invenio_accounts/alembic/843bc79c426f_create_accounts_branch.py
- invenio_accounts/alembic/9848d0149abd_create_accounts_tables.py
- setup.py
- tests/test_invenio_accounts.py
Depends on inveniosoftware/invenio-db#59
> global: initial alembic recipes

- invenio_accounts/alembic/9848d0149abd_create_accounts_tables.py
- invenio_accounts/models.py
Depends on https://github.com/inveniosoftware/invenio-db/pull/66
> models: forced name of Boolean column

- .editorconfig
- .gitignore
- .travis.yml
- .tx/config
- AUTHORS.rst
- CHANGES.rst
- CONTRIBUTING.rst
- INSTALL.rst
- README.rst
- RELEASE-NOTES.rst
- docs/Makefile
- docs/api.rst
- docs/conf.py
- docs/configuration.rst
- docs/examplesapp.rst
- docs/index.rst
- docs/make.bat
- examples/app-fixtures.sh
- examples/app-setup.sh
- examples/app-teardown.sh
- examples/app.py
- invenio_accounts/config.py
- invenio_accounts/ext.py
- run-tests.sh
- setup.cfg
- setup.py
- tests/conftest.py
- tests/test_examples_app.py
* FIX Adds changes according to release preparation checklist.
Signed-off-by: Rémi Ducceschi <remi.ducceschi@gmail.com>
*NOTE*: the USAGE documentation should be updated to give a real use case. Currently, it is the same as the API documentation...
> global: fix release checklist

- docs/api.rst
- docs/conf.py
- invenio_accounts/models.py
- invenio_accounts/proxies.py
- invenio_accounts/tasks.py
- tests/test_tasks.py
* Adds a new task to clean up expired sessions. (addresses #52)
> tasks: new task to clean up expired sessions

- invenio_accounts/config.py
- invenio_accounts/models.py
- invenio_accounts/templates/invenio_accounts/settings/security.html
- invenio_accounts/views.py
- setup.py
- tests/conftest.py
- tests/test_examples_app.py
- tests/test_views.py
* Adds a view to manage the security session table. (addresses #52)
> views: manage security table for the user 

- invenio_accounts/forms.py
- invenio_accounts/templates/invenio_accounts/settings/security.html
- invenio_accounts/views.py
* Improves design of templates a bit.
* Fixes a CSRF issue with revoke form.
> views: view sessions templates and CSRF fix

- invenio_accounts/alembic/9848d0149abd_create_accounts_tables.py
- invenio_accounts/models.py
> models: constraint naming conventions fix

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_accounts/version.py
> release: v1.0.0b2

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_accounts/version.py
@tiborsimko This should fix the bad wheel package on pypi (v1.0.0b2) 
> release: v1.0.0b3

- invenio_accounts/ext.py
- invenio_accounts/sessions.py
- tests/test_examples_app.py
- tests/test_sessions.py
* Removes user session activity entry upon logout. (closes #183)
Needs tests
> sessions: remove sessionactivity upon logout

- invenio_accounts/templates/invenio_accounts/settings/security.html
- invenio_accounts/translations/messages.pot
@inveniosoftware/admins please update sources on Transifex.
> Missing i18n

- examples/app.py
- invenio_accounts/config.py
- invenio_accounts/ext.py
- invenio_accounts/views/__init__.py
- invenio_accounts/views/security.py
- invenio_accounts/views/settings.py
- setup.py
- tests/conftest.py
- tests/e2e/conftest.py
- tests/test_models.py
- tests/test_sessions.py
* Supports disabling session activity tab through configuration.
(closes #201)
> global: support disabling session activity tab

- invenio_accounts/views/__init__.py
* Makes the blueprint importable from views for backward compatibility.
> views: blueprint exposure fix

- invenio_accounts/alembic/e12419831262_add_new_columns_on_sessionactivity.py
- invenio_accounts/models.py
- invenio_accounts/sessions.py
- invenio_accounts/templates/invenio_accounts/settings/security.html
- setup.cfg
- setup.py
- tests/test_invenio_accounts.py
- tests/test_sessions.py
* Adds extra information inside session activity. (addresses #52)
> models: extra info addition on SessionActivity

- invenio_accounts/alembic/e12419831262_add_new_columns_on_sessionactivity.py
- invenio_accounts/models.py
- invenio_accounts/sessions.py
- invenio_accounts/templates/invenio_accounts/settings/security.html
- tests/test_sessions.py
* Renames field operative_system to os. (closes #206)
* Renames field ip_addr to ip.
> models: fix typo in field name

- invenio_accounts/context_processors/jwt.py
- tests/test_template_context_processors.py
* Adds the context processor ``jwt_token`` which generates a jwt token.
> context_processors: addition of ``jwt_token``

- setup.py
- tests/test_examples_app.py
Signed-off-by: Krzysztof Nowak <k.nowak@cern.ch>
> installation: addition of missing passlib dependency

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_accounts/version.py
Signed-off-by: Nicolas Harraudeau <nicolas.harraudeau@cern.ch>
> release: v1.0.0b5

- docs/configuration.rst
- invenio_accounts/config.py
* Fixes wrong documentation for remember me feature.
> docs: correct remember me documentation

- invenio_accounts/ext.py
Signed-off-by: Javier Martin Montull <javier.martin.montull@cern.ch>
> ext: make session permanent by default

- invenio_accounts/templates/invenio_accounts/_macros.html
> templates: update field macro

- invenio_accounts/__init__.py
- invenio_accounts/ext.py
- setup.py
* ADD ui extension class to make session permanent only
in requests from the browser.
(blocks https://github.com/inveniosoftware/invenio-oauth2server/pull/132)
Signed-off-by: Dinos Kousidis <konstantinos.kousidis@cern.ch>
> ext: ui class

- invenio_accounts/ext.py
- invenio_accounts/forms.py
* Disables ``remember me`` option from the login form.
> global: disable ``remember me`` option

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_accounts/version.py
> release: v1.0.0b7

- invenio_accounts/templates/invenio_accounts/settings/security.html
> templates: remove inline style attr

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_accounts/version.py
- setup.py
> release v1.0.0b8

- setup.py
> installation: pin simplekv version to 0.10

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_accounts/version.py
> release: v1.0.0b10

- requirements-devel.txt
> global: fix build error

- invenio_accounts/config.py
- invenio_accounts/ext.py
- invenio_accounts/utils.py
- tests/conftest.py
- tests/test_invenio_accounts.py
* Adding headers about current user/session to the http response.
Closes #247
> ext: add http headers about current user/session

- invenio_accounts/config.py
- tests/conftest.py
- tests/test_tasks.py
- tests/test_token_duration.py
* introduced config security variables for reset and confirm token duration
* tests for token duration
* fix for task tests, registering a route inside a task
* closes #269, #278
> config: faster token expiration

- CHANGES.rst
- invenio_accounts/version.py
> release: v1.1.0

- .travis.yml
- setup.py
> travis: fix build

- setup.py
> setup: add Flask-Admin as an extra

- CHANGES.rst
- invenio_accounts/version.py
- setup.py
* Fixes requirements for Flask, Werkzeug and Flask-Login due to
incompatibilities of latest released modules.
> release: v1.1.2

- .travis.yml
- CHANGES.rst
- examples/app-setup.sh
- invenio_accounts/version.py
- requirements-devel.txt
- setup.py
- tests/e2e/conftest.py
* update flask dependency for centrally managed
* fixed scope mismatch of webdriver test
> global: remove Werkzeug minimal version

- invenio_accounts/templates/semantic-ui/invenio_accounts/forgot_password.html
- invenio_accounts/templates/semantic-ui/invenio_accounts/login_user.html
- invenio_accounts/templates/semantic-ui/invenio_accounts/register_user.html
- invenio_accounts/templates/semantic-ui/invenio_accounts/reset_password.html
> templates: remove stacked segments

- invenio_accounts/templates/semantic-ui/invenio_accounts/login_user.html
- invenio_accounts/templates/semantic-ui/invenio_accounts/register_user.html
- setup.py
- Removes extra whitespace.
- Ensure consistent font size for bottom message on login/signup page.
- Ensure consistent icons for sign up button.
- Define better CSS class for sign up button.
> theme: fix whitespace and sign/login consistency

- invenio_accounts/templates/semantic-ui/invenio_accounts/forgot_password.html
- invenio_accounts/templates/semantic-ui/invenio_accounts/reset_password.html
addresses https://github.com/inveniosoftware/invenio-theme/issues/166
> reset_password: set reset password header class

- invenio_accounts/templates/semantic-ui/invenio_accounts/_macros.html
- invenio_accounts/templates/semantic-ui/invenio_accounts/login_user.html
addresses https://github.com/inveniosoftware/invenio-theme/issues/164
New style:
> login: fix styling in login form

- CHANGES.rst
- invenio_accounts/version.py
> release: v1.4.0a5

- CHANGES.rst
- invenio_accounts/forms.py
- invenio_accounts/templates/semantic-ui/invenio_accounts/login_user.html
- invenio_accounts/templates/semantic-ui/invenio_accounts/register_user.html
- invenio_accounts/version.py
> forms: fixes 'next' redirect in the register form and release v1.4.0a7

- invenio_accounts/templates/semantic-ui/invenio_accounts/login_user.html
- invenio_accounts/templates/semantic-ui/invenio_accounts/register_user.html
*closes https://github.com/inveniosoftware/invenio-app-rdm/issues/255
> styles: Fixes login styling

- docs/api.rst
- docs/conf.py
- invenio_accounts/ext.py
- invenio_accounts/views/rest.py
- pytest.ini
- run-tests.sh
- setup.cfg
- setup.py
- tests/conftest.py
- tests/test_views_rest.py
* fixes redirection after logout from flask-security
> rest: add get method for logout

- docs/api.rst
- docs/conf.py
- invenio_accounts/views/rest.py
- pytest.ini
- run-tests.sh
- setup.cfg
- setup.py
* add GET method to logout
* update to latest pytest-invenio
> update from maint-1.3.

- invenio_accounts/templates/semantic-ui/invenio_accounts/forgot_password.html
* closes https://github.com/inveniosoftware/invenio-theme/issues/210
> style: harmonizes login style

- .github/workflows/tests.yml
- run-tests.sh
> global: migrate CI to GH Actions

- .github/workflows/tests.yml
- run-tests.sh
- setup.py
- tests/test_views.py
- tests/test_views_rest.py
- removed dependencies introduced from pytest-invenio
- replaced backport mock with built in unittest.mock
- closes #349
> tests: remove explicit test dependencies

- invenio_accounts/templates/invenio_accounts/forgot_password.html
- invenio_accounts/templates/invenio_accounts/login_user.html
- invenio_accounts/templates/invenio_accounts/register_user.html
- invenio_accounts/templates/invenio_accounts/reset_password.html
- invenio_accounts/templates/semantic-ui/invenio_accounts/_macros.html
- invenio_accounts/templates/semantic-ui/invenio_accounts/change_password.html
- invenio_accounts/templates/semantic-ui/invenio_accounts/forgot_password.html
- invenio_accounts/templates/semantic-ui/invenio_accounts/login_user.html
- invenio_accounts/templates/semantic-ui/invenio_accounts/register_user.html
- invenio_accounts/templates/semantic-ui/invenio_accounts/reset_password.html
- invenio_accounts/templates/semantic-ui/invenio_accounts/send_confirmation.html
- invenio_accounts/translations/cs/LC_MESSAGES/messages.po
- invenio_accounts/translations/da/LC_MESSAGES/messages.po
- invenio_accounts/translations/de/LC_MESSAGES/messages.po
- invenio_accounts/translations/es/LC_MESSAGES/messages.po
- invenio_accounts/translations/fr/LC_MESSAGES/messages.po
- invenio_accounts/translations/it/LC_MESSAGES/messages.po
- invenio_accounts/translations/messages.pot
- invenio_accounts/translations/tr/LC_MESSAGES/messages.po
- tests/test_views.py
> forms: Fixes errors rendering

- invenio_accounts/templates/semantic-ui/invenio_accounts/forgot_password.html
> styles: Fix reset password bottom footer

- CHANGES.rst
- invenio_accounts/templates/semantic-ui/invenio_accounts/settings/security.html
- invenio_accounts/version.py
> Fix session logout

- docs/configuration.rst
- invenio_accounts/config.py
- invenio_accounts/tasks.py
- tests/test_tasks.py
> tasks: add deletion of login-ips older than 30 days

- setup.py
- tests/test_invenio_accounts.py
This PR requires the changes from https://github.com/inveniosoftware/invenio-rest/pull/126
> Make ready for Flask 2

- invenio_accounts/utils.py
:rotating_light: Please review the [guidelines for contributing](https://invenio.readthedocs.io/en/latest/community/contributing/contribution-guide.html) to Invenio.
> Green light on all GitHub Actions status checks is required in order to merge your PR. Check your code additions will fail neither code linting checks nor tests and will not decrease test coverage.
See [copyright and license policy](https://invenio.readthedocs.io/en/latest/community/contributing/maintainers-guide/copyright-policy.html) for details.
1. …
> utils: remove future import

- .github/workflows/pypi-publish.yml
- setup.py
- tests/conftest.py
- tests/test_cli.py
- tests/test_views.py
Flask 2.1 for master branch
**Reminder**
2. You agree that you have the right to license your …
> global: support Flask v2.1

- invenio_accounts/testutils.py
> testutils: fix flask-login 0.4 compatibility issue

- invenio_accounts/models.py
- tests/test_models.py
**Reminder**
2. You agree that you have the right to license your contribution under the current repository’s license.
> models: allow initialization of profile

- invenio_accounts/models.py
> models: set visibility defaults

- invenio_accounts/api.py
- invenio_accounts/datastore.py
- invenio_accounts/proxies.py
- invenio_accounts/signals.py
- tests/e2e/e2e_basic_test.py
- tests/test_cli.py
- tests/test_hash.py
- tests/test_models.py
- tests/test_sessions.py
- tests/test_utils.py
- closes https://github.com/inveniosoftware/invenio-communities/issues/536
> signals: add datastore pre_commit and post_commit

- babel.ini
- invenio_accounts/translations/de/LC_MESSAGES/messages.po
- invenio_accounts/translations/messages.pot
- invenio_accounts/views/security.py
- invenio_accounts/views/settings.py
* remove jinja extensions
* update `.pot`
* use of `.format` instead of `f-string`
related inveniosoftware/invenio-app-rdm#1664
was this config meant to fetch the value? see: https://github.com/inveniosoftware/invenio-accounts/blob/21ea08bae4c711d684c5005a810f04eb6faf651a/invenio_accounts/utils.py#L209
> i18n: update pot file

- invenio_accounts/templates/security/email/change_notice_rest.html
Refs: https://github.com/inveniosoftware/invenio-app-rdm/issues/1707
Note: this will need some further improvements.
Closes #415
> i18n: Fixes string marked for translation.

- invenio_accounts/views/security.py
- invenio_accounts/views/settings.py
partly closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1742
> icons: fix icons not appearing

- tests/conftest.py
> tests: add teardown handler

- invenio_accounts/templates/semantic-ui/invenio_accounts/change_password.html
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1899
> change password: update errormsg reference for new_password_confirm

- invenio_accounts/config.py
- invenio_accounts/models.py
- tests/test_models.py
This PR introduces the ability to override the default visibility settings for user and email by parameterizing the default visibility. This allows for more flexibility without breaking any existing applications.
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-reposi …
> global: parameterize user and email visibility

- CHANGES.rst
- invenio_accounts/__init__.py
> release: v2.0.2

- invenio_accounts/models.py
- invenio_accounts/profiles/schemas.py
- tests/test_schemas.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2069
> preferences: add support for preferences.locale

- invenio_accounts/templates/semantic-ui/invenio_accounts/change_password.html
- invenio_accounts/templates/semantic-ui/invenio_accounts/forgot_password.html
- invenio_accounts/templates/semantic-ui/invenio_accounts/login_user.html
- invenio_accounts/templates/semantic-ui/invenio_accounts/register_user.html
- invenio_accounts/templates/semantic-ui/invenio_accounts/reset_password.html
- invenio_accounts/templates/semantic-ui/invenio_accounts/send_confirmation.html
- invenio_accounts/templates/semantic-ui/invenio_accounts/settings/security.html
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2301
Accessibility & layout improvements.
> templates: Improve accessibility and layout

- CHANGES.rst
- invenio_accounts/__init__.py
> release: v3.1.0

- invenio_accounts/alembic/037afe10e9ff_add_user_moderation_fields.py
- invenio_accounts/models.py
- tests/test_invenio_accounts.py
closes https://github.com/inveniosoftware/invenio-users-resources/issues/92
> models: added moderation fields

- CHANGES.rst
- invenio_accounts/__init__.py
> release: v3.2.0

- invenio_accounts/alembic/999dcbd19ace_users_versioning.py
- invenio_accounts/alembic/dfbdf43a3e96_separate_login_info.py
- invenio_accounts/alembic/f2522cdd5fcd_change_accountsrole_primary_key_to_string.py
> alembic: fix sqlalchemy op due to latest sqlalchamy-continuum

- CHANGES.rst
- invenio_accounts/__init__.py
> release: v3.2.1

- invenio_accounts/config.py
- invenio_accounts/models.py
closes https://github.com/inveniosoftware/invenio-requests/issues/344
> models: added default verified status.

- invenio_accounts/ext.py
- invenio_accounts/forms.py
- invenio_accounts/templates/semantic-ui/invenio_accounts/send_confirmation.html
> templates: refactor send confirmation template

- CHANGES.rst
- invenio_accounts/__init__.py
> release: v3.4.0

- .github/workflows/tests.yml
- invenio_accounts/forms.py
- invenio_accounts/views/rest.py
* closes https://github.com/zenodo/zenodo-rdm/issues/590
> datastore: prevent autoflush

- invenio_accounts/admin.py
- invenio_accounts/config.py
- invenio_accounts/views/security.py
- setup.cfg
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect on Discord](https://discord.gg/8qatqBC).
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under the …
> I18n-translations-backport

- setup.cfg
Fix the issue where `python setup.py extract_messages` is unable to extract messages that use a different alias instead of _
see: https://babel.pocoo.org/en/latest/setup.html#id1
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect on Discord](https://discord.gg/8qatqBC).
**Frontend**
**Reminder**
1. You license your contribution …
> i18n: add keywords for translation extraction

- CHANGES.rst
- invenio_accounts/__init__.py
- setup.cfg
- fix(setup): pin marshmallow
- release: v5.2.0
> rel v5 2 0

- CHANGES.rst
- invenio_accounts/__init__.py
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect on Discord](https://discord.gg/8qatqBC).
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under the …
> Release v5.2.1
