inveniosoftware/invenio-accounts

invenio_accounts/models.py
* FIX Changes index definition in `UserEXT` model for `id_user`
column.  (closes #5)
=> models: fix unique index on userEXT.id_user column

invenio_accounts/upgrades/accounts_2015_06_26_userext.py, invenio_accounts/upgrades/accounts_2015_07_10_nickname_check_rules_changed.py
* FIX Adds return value to `userext` estimate method and fixes the
table name.
* FIX Nickname check rules uses only the nickname column instead of all
of them.
Signed-off-by: Esteban J. G. Gabancho <esteban.gabancho@gmail.com>
=> upgrader: upgrade recipes fix

invenio_accounts/helpers.py, invenio_accounts/utils.py
* Moves invenio_accounts.helpers.send_account_activation_email to
invenio_accounts.utils.send_account_activation_email.
* Deprecates invenio_accounts.helpers.send_account_activation_email.
=> global: unifies helpers and utils into utils.py

.travis.yml, MANIFEST.in, invenio_accounts/bundles.py, invenio_accounts/forms.py, invenio_accounts/models.py, invenio_accounts/upgrades/accounts_2015_01_14_add_name_columns.py, invenio_accounts/upgrades/accounts_2015_03_06_namedefaults.py, invenio_accounts/upgrades/accounts_2015_03_06_passlib.py, invenio_accounts/upgrades/accounts_2015_06_26_userext.py, invenio_accounts/upgrades/accounts_2015_07_10_nickname_check_rules_changed.py, invenio_accounts/utils.py, invenio_accounts/views/accounts.py, invenio_accounts/views/settings.py, pytest.ini, requirements-devel.txt, setup.py, tests/test_accounts_user.py, tests/test_forms.py, tests/test_tokens.py
* FIX pytest 2.8.0 removed functionality used for tests. This removes
calls to the removed functions.
=> tests: fix pytest >=2.8.0 breaking

invenio_accounts/ext.py, setup.py
* Adds entry point for Invenio-Base to discover Flask extension.
* Removes assertion on having Invenio-DB and Flask-Mail installed.
=> installation: entry point addition

AUTHORS.rst, invenio_accounts/ext.py
* Enables the use of Celery during the Invenio-Accounts
extension configuration only if Celery is available in the
system installation. (Closes #27)
Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>
=> global: fix ACCOUNTS_USE_CELERY behaviour

setup.py
* Fixes a small typo from 'acconts' to 'accounts' in setup.py
entrypoints.
=> accounts: fix typo acconts -> accounts

invenio_accounts/templates/invenio_accounts/change_password.html, invenio_accounts/templates/invenio_accounts/forgot_password.html, requirements-devel.txt, setup.py, tests/conftest.py, tests/test_invenio_accounts.py, tests/test_views.py
* Removes 'Log In or Sign Up' message from the password reset form for
logged in users. (closes #35)
=> templates: reset form fix for logged in users

.gitignore, MANIFEST.in, invenio_accounts/translations/messages.pot
* Adds missing .pot file to version control. (closes #24)
* Adds *.pot files to MANIFEST.in
* Removes *.pot from .gitignore
Signed-off-by: Sami Hiltunen <sami.mikael.hiltunen>
=> i18n: addition of missing .pot file

setup.py
* Fixes problem with ipaddr requirement not being installed from
SQLAlchemy-Utils[ipaddress] extra requirement.
=> installation: ipaddr requirements fix

setup.py
* Makes a wheel generated on Python 2.7 universal for Python 3.3+.
(closes #57)
=> installation: fix for ipaddr in wheel on PY3

invenio_accounts/testutils.py, tests/test_utils.py
Adds utility functions for testing purposes:
- `client_authenticated` which checks if the current client is authenticated by attempting to access the "change password" form/view (requires app context and a client)
- `create_test_user` which creates a new user from the given arguments and returns the user object, with its plaintext password as an additional field (`password_plaintext`) (requires app context)
- `login_user_via_view(client, email, password)` which logs the user in via the login page (requires app context and a client).
Ideally the login utility would just log the user in and return the valid session which we could then attach to a client. However I've not been able to figure out how flask creates and attaches the session to the client, and my efforts to …
=> tests: addition of authentication utility functions

invenio_accounts/ext.py
Changes configuration to not use celery by default for sending email in debug and testing mode.
When you bootstrap a new site:
```console
$ inveniomanage instance create mysite
$ cd mysite
$ mysite --debug run
```
and afterwards go register a new account it will fail if you don't have rabbitmq running (like wise [this fix](https://github.com/inveniosoftware/invenio-base/commit/635498f37ddf339c595293aab4b7bf91fc5df9cb) ensures that the mail is printed to the console).
This only happens when ``--debug`` is specified and can be overwritten in the overlay config to always use celery.
=> ext: celery use in debug mode change

invenio_accounts/testutils.py, tests/test_utils.py
Passing no args to `testutils.py:create_test_user` created a user with the empty string as its password. Logging in doesn't work with such a user. This wasn't caught as all of the tests for `create_test_user` explicitly passed email and password.
The PR contains a test for the default values of `create_test_user`, and changes the default value of its `password` kwarg to a non-empty string.
=> tests: default user password fix

invenio_accounts/templates/invenio_accounts/login_user.html
* FIX Fixes css classes for icons to use font awesome instead of glyphicons.
Signed-off-by: Eamonn Maguire <eamonnmag@gmail.com>
=> template: fontawesome icon fix

.travis.yml, MANIFEST.in, docs/usage.rst, invenio_accounts/testutils.py, setup.py, tests/e2e/conftest.py, tests/e2e/e2e_basic_test.py, tests/test_utils.py
* Adds E2E/integration tests in `tests/e2e/`, and necessary changes to get them running locally and on Travis.
* Parametrizes the E2E tests via an environment variable and override of pytest's `pytest_generate_tests` in `tests/e2e/conftest.py`.
* Changes some existing tests to work with `pytest-flask`, which provides useful fixtures for e2e-testing.
=> tests: e2e/integration tests

examples/app.py, invenio_accounts/cli.py, tests/test_cli.py
* Uses argument instead of option for required parameters. (closes #56)
=> cli: unify arguments and options

invenio_accounts/ext.py, invenio_accounts/tasks.py, tests/test_tasks.py
* Fixes default serializer of task sending Flask-Mail messages.
(closes #81)
=> global: fix Message serialization for celery

.travis.yml, e2e_setup.sh
Not sure about the co-authored/signed-off-by attribution -- I've basically copied what Lars did in Zenodo.
This commit increases the Travis job count by 4 (one per Python version), meaning the total job count per build is now 40.
The E2E tests are excluded from 36 of the jobs (which now only run the unit tests), and run once in each of the four new jobs.
Does this reduce the overall build time?
- Old build time: `J * (tu + te) + JS`
- New build time: `S * (J + K) + J * tu + J * te)
- `J` is the number of jobs per build before this commit, `K` is the number of jobs added by this commit, `S` is the startup/setup time of a Travis job, `tu` is the avg. run time of the unit tests, `te` is the avg. run time of the E2E tests.
- If `J * te > K * (S + te)` (it takes less time to set up `K` travis …
=> tests: separate E2E test build matrix on Travis

invenio_accounts/templates/invenio_accounts/forgot_password.html, invenio_accounts/templates/invenio_accounts/reset_password.html, invenio_accounts/views.py, setup.cfg
* Fixes missing string translation in templates.
* Adds lazy translation of settings menu item.
* Adds extraction of translation notes.
* Adds reset password template.
=> global: i18n fixes

invenio_accounts/templates/invenio_accounts/register_user.html
* Adds blocks that allow hooking into the registeration template
before and after the username and password fields.
(required by inveniosoftware/invenio-userprofiles#13)
=> views: registration template block

invenio_accounts/config.py, invenio_accounts/ext.py
* Adds 'ACCOUNTS_SESSION_REDIS_URL' as a configurable variable to set the redis connection parameters. If not present, the default localhost:6379/0 parameters as used. (closes #99)
Signed-off-by: Eamonn Maguire <eamonnmag@gmail.com>
=> config: allow for configuration of Redis session connection

tests/e2e/conftest.py
* Disables E2E tests locally by default. They can still be run by
setting E2E_WEBDRIVER_BROWSERS.
=> tests: E2E tests disabled locally by default

invenio_accounts/ext.py, invenio_accounts/models.py, invenio_accounts/sessions.py, invenio_accounts/testutils.py, tests/conftest.py, tests/e2e/conftest.py, tests/test_admin.py, tests/test_cli.py, tests/test_invenio_accounts.py, tests/test_models.py, tests/test_sessions.py, tests/test_utils.py, tests/test_views.py
- Refactors tests and improves test coverage.
- Removes `id` column from SessionActivity as `sid_s` should be __the__ primary key.
--
closes #108
=> global: transactions for session activity and coverage

AUTHORS.rst, invenio_accounts/ext.py, tests/conftest.py, tests/test_sessions.py
* Adds an in-memory KVSession DictStore cache. Running tests locally
no longer requires Redis. Travis will still run with Redis.
=> tests: addition of in-memory KVSession cache

examples/app.py
* Removes menu initialization when InvenioTheme is enabled.
(closes #10)
=> examples: Menu initializion fix

invenio_accounts/__init__.py, invenio_accounts/config.py, invenio_accounts/ext.py, setup.py, tests/test_invenio_accounts.py
* Separates REST extension that does not register blueprint.
(closes #120)
--
cc @nharraud
=> ext: separate REST extension

AUTHORS.rst, invenio_accounts/ext.py, invenio_accounts/hash.py, setup.py, tests/test_hash.py
* NEW Adds the ability to migrate legacy Invenio users to Invenio 3
automatically. The old encryption scheme has been integrated into the
flask-security extension and a `migrate_hash` function can be used to
update the password by re-encrypting it (using the current hash
scheme) and storing it in the datastore. (closes #122)
* Adds a new test utility, namely `create_legacy_user`.
* Increases test coverage.
Signed-off-by: Orestis Melkonian <melkon.or@gmail.com>
Co-Authored-By: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>
=> global: support for legacy invenio password hashes

docs/conf.py, invenio_accounts/views.py
* FIX Fixes issue of `change_password` registration, even when the
configuration `variable SECURITY_CHANGEABLE` was set to `False`.
Signed-off-by: Orestis Melkonian <melkon.or@gmail.com>
=> views: allow CHANGEABLE to be False

RELEASE-NOTES.rst, examples/app.py, invenio_accounts/translations/da/LC_MESSAGES/messages.po, invenio_accounts/translations/messages.pot, setup.cfg, setup.py, tests/test_cli.py, tests/test_invenio_accounts.py, tests/test_views.py
* Changes `invenio-software.org` to `inveniosoftware.org` to use the
same dashless canonical ID everywhere (GitHub, Twitter, Web).
=> global: inveniosoftware.org

invenio_accounts/testutils.py, tests/e2e/e2e_basic_test.py, tests/test_hash.py, tests/test_models.py, tests/test_sessions.py, tests/test_utils.py
* Makes email address a required argument in `create_test_user`
function.  (closes #93)
=> tests: user creation with required email address

invenio_accounts/views.py
Since Invenio should be running over SSL, this option sets the secure flag on the session cookie to avoid session stealing through a man-in-the-middle attack. (I believe this will break login over insecure connections, but @kaplun suggested that we can just set up SSL on INSPIRE Nightly.)
Signed-off-by: Liam Kirsh <liam.kirsh@cern.ch>
=> config: turn on secure session cookie flag

invenio_accounts/forms.py, setup.py
We just began seeing this warning:
```
class ChangePasswordForm(Form, PasswordFormMixin):
/Users/jacquerie/.virtualenvs/inspire/lib/python2.7/site-packages/invenio_accounts/forms.py:34:
FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be
removed in 1.0.
```
This PR bumps `Flask-WTF` to 0.13 and updates the API correspondingly to suppress this warning.
=> global: Flask-WTF upgrade to 0.13

setup.py
* Fixes issue with Celery task not being registered.
=> installation: celery task entry point

setup.py
* Fixes issue with environment markers supported by setuptools and pip
not being handled properly by wheel.
=> installation: environment marker fix

invenio_accounts/sessions.py, requirements-devel.txt, setup.cfg
* Fixes logout issue in tests by deleting the user session in an
after_this_request function instead of doing it immediately.
(closes #197)
Signed-off-by: Nicolas Harraudeau <nicolas.harraudeau@cern.ch>
=> global: delete session after logout request

examples/app.py, examples/templates/authenticated.html, invenio_accounts/admin.py, invenio_accounts/sessions.py, setup.py, tests/conftest.py, tests/test_admin.py
* Adds a session administration page. (addresses #52)
* Commits the session when login permit to fix the session creation
on user first signup. (closes #190)
=> admin: session administration addition, session creation on sign-up

invenio_accounts/config.py, invenio_accounts/context_processors/__init__.py, invenio_accounts/context_processors/jwt.py, invenio_accounts/errors.py, invenio_accounts/ext.py, invenio_accounts/templates/invenio_accounts/jwt.html, invenio_accounts/utils.py, setup.py, tests/test_template_context_processors.py, tests/test_utils.py
* Adds support for JWT (jwt.io), which is enabled by default. All the
protected endpoints ``require_api_auth`` will be automatically
check for JWT in the headers. A token can be generated by using the
``{{ jwt() }}`` context processor in jinja templates and can
be send with each API request.
=> global: addition of JWT

invenio_accounts/alembic/9848d0149abd_create_accounts_tables.py
* Fixes a bug where the name of the foreign key constraint between
the "transaction" table and the "accounts_user" table was random.
(closes #219)
Signed-off-by: Nicolas Harraudeau <nicolas.harraudeau@cern.ch>
=> models: fix alembic foreign key naming

invenio_accounts/config.py, invenio_accounts/ext.py, tests/conftest.py, tests/test_invenio_accounts.py
* Add secure default config for "remember me" -cookie.
By default matches mostly to configuration of session-cookie.
Signed-off-by: Harri Hirvonsalo <harri.hirvonsalo@cern.ch>
=> security: secure by default configuration

CHANGES.rst, RELEASE-NOTES.rst, invenio_accounts/version.py, setup.py
Solves installation issues on Python3 and Travis:
https://travis-ci.org/zenodo/zenodo/jobs/257306470#L1391
This was most likely because of some travis pip cache issue and/or requirements-builder.
The version marker which install ipaddr directly on Python 2 produces the same effect as the removed extras kwarg: https://github.com/kvesteri/sqlalchemy-utils/blob/master/setup.py#L47
=> SQLAlchemy-Utils extras fix

invenio_accounts/cli.py, invenio_accounts/ext.py, invenio_accounts/testutils.py, setup.py, tests/test_admin.py, tests/test_hash.py, tests/test_utils.py
Same motivation as https://github.com/inveniosoftware/flask-security-fork/pull/28, but different implementation: here I'm not deprecating `encrypt_password`, I'm outright removing it.
Consequently, I switch from `Flask-Security-Fork` to `Flask-Security>=3.0.0`, which is guaranteed to contain the commit I introduced above. The other two changes in `setup.py` are required to match the minimal version of the packages required by `Flask-Security>=3.0.0`.
=> global: encrypt_password -> hash_password

invenio_accounts/ext.py, tests/test_invenio_accounts.py, tests/test_views.py
* Disables remember me token generation. (closes #226)
* Disables login from headers. 
* Disables login from request. (closes #231)
=> ext: disable remember me token generation and login from header

setup.py
* Adds an upper bound version ``2.6`` for ``idna`` module until the next
``requests`` is released. More details are in the following commit
https://github.com/requests/requests/commit/f4ddf00c364e4396e7d941f91a8817311dd79adc
which support ``2.6`` version. (closes inveniosoftware/invenio-app-ils#33)
=> setup: upper bound for ``idna``

invenio_accounts/admin.py
Apologies for the trivial PR, but https://github.com/inveniosoftware/invenio-accounts/pull/229 missed one last use of `encrypt_password` that was introduced after I created that commit.
=> admin: remove one last encrypt_password

CHANGES.rst, RELEASE-NOTES.rst, invenio_accounts/sessions.py, invenio_accounts/version.py, setup.py
Closes https://github.com/inveniosoftware/invenio-accounts/issues/247.
First commit bumps the minimum version of `cryptography`
to the version required by the version of `OpenSSL` that is
there (see: https://github.com/pyca/pyopenssl/issues/728).
In Flask-KVSession, a session without a ``sid_s`` attribute is
equivalent to one that set it to ``None``, so we shouldn't be
assuming that it's there (see: https://github.com/mbr/flask-kvsession/commit/a04957d91d1a9146e3b83445c10d9e5273365af3).
Last commit asks for a release, as this is a bug we're seeing
on a production system : )
=> sessions: don't require sid_s to be there

setup.py
Version 0.11.2 of simplekv restored the old behavior of accepting
keys of type ``str`` in Python 2.
=> setup: simplekv unpin

docs/conf.py, invenio_accounts/config.py, invenio_accounts/ext.py, tests/conftest.py, tests/test_invenio_accounts.py
* Updates configuration setting ACCOUNTS_SESSION_REDIS_URL to
empty string by default, what makes Invenio-Accounts use in memory
store. Documentation updated accordingly.
* Configures test application to use Redis when running on travis
builds (closes #266).
=> ext: set kvsessionstore at config loading

invenio_accounts/admin.py
* Fixes a small issue that a hashed password is rehashed when saving a user account info in admin view.
=> admin: avoid rehashing of hashed password

CHANGES.rst, invenio_accounts/version.py, setup.py
* replaces flask-celeryext with invenio-celery
* removes Flask-BabelEx already required by invenio-i18n
=> global: update dependencies

CHANGES.rst, invenio_accounts/version.py, setup.py
This is a 'quick' fix for the 2.3.1 breaking change in wtforms
that requires the email-validator library. WTForms is brought in
from flask-security and flask-security is a dependency of
invenio-accounts.
The real fix would be switching to [flask-security-too](https://wtforms.readthedocs.io) since
flask-security is not maintained anymore. However, a cursory attempt
has generated more errors. So until we can address those errors,
this fix can do. (things like `security.forgot_password` not resolving to a route...)
- also fixes pytest dependency issues
=> dependencies: fix missing email_validator [more]

invenio_accounts/views/rest.py, tests/test_views_rest.py
This validation makes sense when registering but not when logging in.
=> rest: remove password length validation from login

invenio_accounts/translations/cs/LC_MESSAGES/messages.po, invenio_accounts/translations/de/LC_MESSAGES/messages.po, invenio_accounts/translations/es/LC_MESSAGES/messages.po, invenio_accounts/translations/fr/LC_MESSAGES/messages.po, invenio_accounts/translations/it/LC_MESSAGES/messages.po, invenio_accounts/translations/messages.pot, invenio_accounts/translations/tr/LC_MESSAGES/messages.po
Closes #346 
The strings were manually removed. However, when created the `fuzzy` string is added. Another option is to force transifex to include fuzzy (add `-f` flag, see [here](https://github.com/inveniosoftware/invenio-app-rdm/issues/230)).
There are [173 files with this problem in Invenio](https://github.com/search?q=org%3Ainveniosoftware+fuzzy&type=code), @lnielsen maybe we could somehow use the automation tools to remove this line?
=> translations: remove fuzzy

invenio_accounts/cli.py, run-tests.sh
- Removes deprecated csrf_enabled usage from Flask-WTF (closes #379).
Replaces and closes #380
=> cli: fix CLI user registration

invenio_accounts/alembic/eb9743315a9d_add_userprofile.py, invenio_accounts/config.py, invenio_accounts/models.py, invenio_accounts/profiles/__init__.py, invenio_accounts/profiles/dicts.py, invenio_accounts/profiles/schemas.py, invenio_accounts/utils.py, tests/test_models.py, tests/test_validated_dicts.py
In this pull request, we introduce JSON-based fields for user profiles, which use configurable marshmallow schemas for validation of manipulation operations before their actual execution.
While this introduces additional overhead for each of the manipulation operations, we do not think that this should be a big issue because updates to user profiles are a rare operation.
Investigations showed that other Invenio modules would often use the `User` model directly rather than helpers like the datastore (e.g. to query for users), and it would thus be beneficial to not introduce extra API functions for user manipulation.
This PR enables operations like the following on users:
```python
In [6]: user.user_profile = {"full_name": "Max Moser", "username": "max-moser"}
In [7]: user.user_profile …
```
=> models: add user profiles as a validated json field

invenio_accounts/profiles/schemas.py, invenio_accounts/sessions.py
Add the `visibility` and `email_visibility` settings to the default user preferences schema, as per discussion on https://github.com/inveniosoftware/invenio-users-resources/pull/15.
Also use a fallback value for `_user_id` in the session if it's not available.
=> User preferences schema

invenio_accounts/config.py, invenio_accounts/utils.py
Closes #415.
Refs https://github.com/inveniosoftware/invenio-app-rdm/issues/1707
=> i18n: Fixing mark for translation.

run-tests.sh
This is to make sure all marked strings are actually extractable.
=> tests: adds extract_messages dry command

invenio_accounts/utils.py, setup.cfg, tests/test_utils.py
* adds a new option to fine tune when to send the registration e-mail and not relying only on the global security configuration.
=> register: option to avoid sending e-mail

CHANGES.rst, invenio_accounts/__init__.py, invenio_accounts/admin.py, invenio_accounts/config.py, invenio_accounts/ext.py, invenio_accounts/forms.py, invenio_accounts/profiles/schemas.py, invenio_accounts/tasks.py, invenio_accounts/utils.py, invenio_accounts/views/security.py, invenio_accounts/views/settings.py, run-tests.sh, setup.cfg, tests/conftest.py, tests/e2e/conftest.py, tests/test_admin.py, tests/test_cli.py, tests/test_invenio_accounts.py, tests/test_views.py, tests/test_views_rest.py
- migrate: flask_babelex replaced by invenio_i18n
- refactor: remove unused statements
- NOTES:
- to make this testable it is necessary to release invenio-i18n, flask-security-invenio and invenio-theme
=> migrate to flask babel

invenio_accounts/cli.py, tests/test_cli.py
Adds -p/--profile option to `invenio users create` to supply a profile at time of user creation. This enables users to be created on the command line with their full name (and/or other profile items set) configured. 
eg `invenio users create -a -c -p '{"full_name" : "Test User"}'  test@example.com`
(Motivation: a user created above is created with enough details set to make the searchable, in the /api/users endpoint, without the need for the user to modify their profile (nb: also requires default profile/email visibility to be set to public in invenio.cfg))
Discussed with @slint.
If you've added [third-party code (copy/pasted or new …
=> cli: create user with profile

invenio_accounts/alembic/f2522cdd5fcd_change_accountsrole_primary_key_to_string.py, invenio_accounts/api.py, invenio_accounts/cli.py, invenio_accounts/datastore.py, invenio_accounts/models.py, run-tests.sh, setup.cfg, tests/test_invenio_accounts.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2186
=> datastore: add update_role func 

invenio_accounts/sessions.py
Dependd on inveniosoftware/flask-security-fork#60
=> session: handle user impersonation

invenio_accounts/models.py
* closes https://github.com/zenodo/rdm-project/issues/521
=> model: avoid setting value on getter

invenio_accounts/alembic/6ec5ce377ca3_create_domains.py, invenio_accounts/datastore.py, invenio_accounts/domains.py, invenio_accounts/ext.py, invenio_accounts/forms.py, invenio_accounts/models.py, invenio_accounts/utils.py, invenio_accounts/views/rest.py, tests/test_models.py, tests/test_views.py, tests/test_views_rest.py
New domain list feature that is used to:
- disallow user registration from specific email domains
- automatically verify users from specific email domains.
- gather statistics about number of users (and their state) in each domain to help identify high-risk domains
- connect domains with known organisations to allow for reporting and identifying low-risk domains.
=> global: new domain list feature

CHANGES.rst, invenio_accounts/__init__.py, invenio_accounts/models.py
Closes https://github.com/zenodo/rdm-project/issues/652
- models: fix column type for domain status
- release: v4.0.1
=> Fix Domain.status column type and release v4.0.1

invenio_accounts/api.py, invenio_accounts/datastore.py, invenio_accounts/domains.py, invenio_accounts/models.py, invenio_accounts/tasks.py
-  Fixes an issue where a newly uncommitted user would not yet have an id assigned, and hence would cause None value to be added to a list of user ids that needed to be reindexed, causing the indexing to fail due to transaction rollback.
- Add change tracking of domains to reindex on updates.
- Add task to compute domain statistics on a regular basis.
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2575 …
=> Models: Domain statistics and model change history tracking fixes

CHANGES.rst, invenio_accounts/__init__.py, invenio_accounts/models.py, tests/test_models.py
Fixes https://github.com/zenodo/ops/issues/326
Usernames are enforced to be unique in the DB regardless of their case ([see related DB column and constraint definition](https://github.com/inveniosoftware/invenio-accounts/blob/master/invenio_accounts/alembic/eb9743315a9d_add_userprofile.py#L53-L66)).
This change proposes to compare usernames case-insensitively.
This will avoid problems like users trying to sign up with an existing username but with a different case, which are currently hitting the DB constraint and then showing an nginx 502 error since it is not well handled by Flask.
If you've added [third-party code (copy/pasted or new …
=> Models: fix username case-insensitive comparator & release: v5.0.1

CHANGES.rst, invenio_accounts/__init__.py, invenio_accounts/views/security.py
Closes #491 
The resulting security page when impersonating users:
It may look a little strange, but i consider that better than a 500 internal server error :smile:
=> security: filter out master_session if it's set to `None`

invenio_accounts/templates/semantic-ui/invenio_accounts/forgot_password.html, invenio_accounts/templates/semantic-ui/invenio_accounts/reset_password.html
Close https://github.com/inveniosoftware/invenio-accounts/issues/496
Before and after
Before and after
Once this is merged I'll remove the [`reset-password` rule](https://github.com/inveniosoftware/invenio-theme/blob/ac24121619048f08c4d084f52dadc14599c2b948/invenio_theme/assets/semantic-ui/less/invenio_theme/theme/elements/header.overrides#L6) as it will no longer be used
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/archit …
=> UI: fix spacing on password reset form

invenio_accounts/datastore.py
(Part of) Close https://github.com/inveniosoftware/invenio-app-rdm/issues/2777
[We call `mark_changed`](https://github.com/carlinmack/invenio-accounts/blob/commit-domain/invenio_accounts/domains.py#L23) but we did not check that it handled Domains
Calling flush as similarly done in the [pre-commit hook](https://github.com/inveniosoftware/invenio-users-resources/blob/master/invenio_users_resources/records/hooks.py#L31)
Also remove setting of role.id as the added flush() will add the ID from DB
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/comm …
=> bug: add handler for handling changed domain

.github/workflows/pypi-publish.yml, .github/workflows/tests.yml, CHANGES.rst, invenio_accounts/__init__.py, invenio_accounts/utils.py, setup.cfg
- setup: pin dependencies
- setup: change to reusable workflows
- release: v5.1.6
=> pin dependencies

invenio_accounts/admin.py, invenio_accounts/config.py, invenio_accounts/views/security.py
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Frontend**
**Reminder** …
=> i18n: Mark Missing Strings for Translation

.github/workflows/pypi-publish.yml
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect on Discord](https://discord.gg/8qatqBC).
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under the …
=> Add-missing-compile-step-in-publish

invenio_accounts/ext.py
* find_spec raises ValueError if the spec is not found
=> fix: find_spec raise ValueError
